version: "3.1"

services: 
    
    mysql:
        image: mysql:8.0.25
        container_name: mysql-java
        ports: 
            - 3306:3306
        environment: 
            MYSQL_USER: java
            MYSQL_PASSWORD: java
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: java

    jaeger:
        image: jaegertracing/all-in-one:1.23
        container_name: jaeger
        ports:
            - 5775:5775/udp
            - 6831:6831/udp
            - 6832:6832/udp
            - 5778:5778
            - 16686:16686
            - 14268:14268
            - 14250:14250
            - 9411:9411